apiVersion: v1
kind: Secret
metadata:
  name: session-secret
type: Opaque
data:
  SESSION_SECRET: bXlfc2VjcmV0

---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_PRIVATE_KEY: bXlfa2V5

---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  ADMIN_EMAIL: a2lydGhpa3N1YmJpYWhAZ21haWwuY29t
  ADMIN_PASSWORD: S2lydGhpaToyMDAz
  ADMIN_COOKIE_NAME: bXlfY29va2ll
  ADMIN_COOKIE_PASSWORD: Q29va2llOjIwMDM=
